### ISSUE TITLE
A few notes to make the code runnable

### ISSUE THREAD

**Issue by llinfeng** [chr-huber/num-comp#2]
1. The "app name" is `num_comp`. This repo's name is a bit misleading.
2. In the HTML files, `{% load humanize %}` may break the local server. Deleting the line gets the code to run.
3. In `Num1.html`, `Num2.html` and `Num3.html`, need to replace `num` as `num_comp` in the first line:
```
{% extends "num/Num0.html" %}
{% load staticfiles otree %}
{% load i18n %}
```

----

@chr-huber Thanks a lot for sharing your code. The instructions are very clear!

**Comment by chr-huber** [comment]
Thanks! I tried to fix all the issues.

1. "app name" has been renamed to ``numcomp``, the repo name to ``numeracy-task-competitiveness`` for clarity
2. ``{% load humanize %}`` has been removed from all HTML files
3.  ``num`` has been replaced by ``numcomp`` in all relevant HTML files
